"""empty message

Revision ID: faf5be6d44ef
Revises: 00bcb79d5835
Create Date: 2019-10-27 16:09:37.115324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf5be6d44ef'
down_revision = '00bcb79d5835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_row', sa.Text(), nullable=True),
    sa.Column('response_row_row', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('bin', sa.Integer(), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=True),
    sa.Column('borocode', sa.Integer(), nullable=True),
    sa.Column('borough', sa.Text(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('community_board', sa.Integer(), nullable=True),
    sa.Column('council_district', sa.Integer(), nullable=True),
    sa.Column('census_tract', sa.Integer(), nullable=True),
    sa.Column('bbl', sa.BigInteger(), nullable=True),
    sa.Column('nta_neighborhood_tabulation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('street_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildings')
    # ### end Alembic commands ###
